config/routes.rb
Rails.application.routes.draw do
 root :to => 'home#index'

get 'home/about', to: 'home#new'


devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}

	
	resources :users
	


	resources :books
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, 
  			presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user,   only: [:edit, :update]




def index
	@user = current_user
	@users = User.all
	@book = Book.new
end

def show
	@user = User.find(params[:id])
	@users = User.all
	@book = Book.new
end

def correct_user
    @user = User.find(params[:id])
    unless @user == current_user
    redirect_to new_user_session_path
end
end


def edit
	@user = User.find(params[:id])
	
end

def update
	@user = User.find(params[:id])
	if @user.update(user_params)
		flash[:notice] = "User was successfully updated."
		redirect_to user_path(current_user.id)
	else
		render :edit
	end
end

private
def user_params
	params.require(:user).permit(:name, :introduction, :profile_image)
end
 def correct_user
      @user = User.find(params[:id])
       unless @user == current_user
      redirect_to user_path(current_user.id)
    end
end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_footer.html.erb
  <footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/users/_header.html.erb
<header class="navbar navbar-fixed-top w-100 navbar-inverse">
	<div class="container fluid">
        <nav class="nav navbar-nav navbar-left">
			<span class=" h3 text-muted">Bookers</span>
		</nav>
			<nav>
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
					<li class="nav-item"><%= link_to user_path(current_user.id) do %>
						<span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span></li><% end %>
					</li>
					<li class="nav-item"><%= link_to users_path do %>
						<span class="glyphicon glyphicon-user" aria-hidden="true"> Users</span></li><% end %>
					<li class="nav-item"><%= link_to books_path do %>
						<span class="glyphicon glyphicon-book" aria-hidden="true"> Books</span></li><% end %>
					<li class="nav-item"><%= link_to destroy_user_session_path, method: :delete do %><span class="glyphicon glyphicon-log-out" aria-hidden="true"> logout</span></li><% end %>
					<% else %>
					<li class="nav-item"><%= link_to root_path do %>
						<span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span></li><% end %>
					<li class="nav-item"><%= link_to home_about_path do %>
						<span class="glyphicon glyphicon-link" aria-hidden="true"> About</span></li><% end %>
					<li class="nav-item"><%= link_to new_user_registration_path do %><span class="glyphicon glyphicon-check" aria-hidden="true"> sign up</span></li><% end %>
					<li class="nav-item"><%= link_to new_user_session_path do %>
						<span class="glyphicon glyphicon-log-in" aria-hidden="true"> login</span></li><% end %>
					<% end %>
				</ul>
			</nav>
	</div>
</header>



<div class="container">
	<p id="notice"></p>

<div class="row">
	<div class="col-xs-3">
	<h1>User info</h1>
		<table class="table">
			<tr><%= attachment_image_tag user, :profile_image, size:"100x100" , fallback: "no_iamge.jpg"%></tr>
			<tr>
				<th>name</th>
				<th><%= user.name %></th>
			</tr>
			<tr>
				<th>introduction</th>
				<th><%= user.introduction %></th>
			</tr>
		</table>
		<%= link_to edit_user_path(@user.id), class:'btn btn-primary btn-block' do %>
		<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
		<% end %>

app/views/users/_userinfo.html.erb
<h2>New book</h2>
		<%= form_for(book) do |f| %>
			<% if book.errors.any? %>
				<div class="alert-alert-warinig">
					<p class="error-count"><%= book.errors.full_messages.count %>errors prohibited this book from being saved:</p>
						<ul>
							<% book.errors.full_messages.each do |message| %>
							<li><%= message %></li>
							<% end %>
						</ul>
				</div>
		<% end %>
		<%= f.label :title, "Title" %>
		<%= f.text_field :title %>

	 	<%= f.label :body, "Body" %>
		<%= f.text_area :body %>

		<%= f.submit :class=> "btn btn-primary btn-block" %>
		<% end %>
	</div>

app/views/users/edit.html.erb
<header class="navbar navbar-fixed-top w-100 navbar-inverse">
	<div class="container fluid">
        <nav class="nav navbar-nav navbar-left">
			<span class=" h3 text-muted">Bookers</span>
		</nav>
			<nav>
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
					<li class="nav-item"><%= link_to user_path(current_user.id) do %>
						<span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span></li><% end %>
					</li>
					<li class="nav-item"><%= link_to users_path do %>
						<span class="glyphicon glyphicon-user" aria-hidden="true"> Users</span></li><% end %>
					<li class="nav-item"><%= link_to books_path do %>
						<span class="glyphicon glyphicon-book" aria-hidden="true"> Books</span></li><% end %>
					<li class="nav-item"><%= link_to destroy_user_session_path, method: :delete do %><span class="glyphicon glyphicon-log-out" aria-hidden="true"> logout</span></li><% end %>
					<% else %>
					<li class="nav-item"><%= link_to root_path do %>
						<span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span></li><% end %>
					<li class="nav-item"><%= link_to home_about_path do %>
						<span class="glyphicon glyphicon-link" aria-hidden="true"> About</span></li><% end %>
					<li class="nav-item"><%= link_to new_user_registration_path do %><span class="glyphicon glyphicon-check" aria-hidden="true"> sign up</span></li><% end %>
					<li class="nav-item"><%= link_to new_user_session_path do %>
						<span class="glyphicon glyphicon-log-in" aria-hidden="true"> login</span></li><% end %>
					<% end %>
				</ul>
			</nav>
	</div>
</header>

<h1>User info</h1>


<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
	<div class="alert-alert-warinig">
		<p class="error-count"><%= @user.errors.full_messages.count %>errors prohibited this book from being saved:</p>
		<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>

    <% end %>
	<p>Name</p>
		<%= f.text_field :name %>
	
    <p>image</p>
		<%= f.attachment_field :profile_image %>

	<p>Introduction</p>
		<%= f.text_area :introduction %>


		<%= f.submit 'Update User' %>
<% end %>

<%= render 'users/footer' %>

app/views/users/index.html.erb
<%= render 'users/header', user: @user %>


<%= render 'users/userinfo', book: @book %>



<div class="col-xs-9">
	<h2>Users</h2>
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>
			<% @users.each do |user| %>
			<tbody>
				<tr>
					<th><%= attachment_image_tag user, :profile_image, size:"40x40", fallback: "no_iamge.jpg" %></th>
					<th><%= user.name %></th>
					<th><%= link_to user_path(user) do %>
						<span class="text-muted">Show</span><% end %></th>
				</tr>
			</tbody>
			<% end %>
		</table>
</div>
</div>
</div>
<%= render 'users/footer' %>

app/views/users/show.html.erb
<%= render 'users/header', user: @user %>

<%= render 'users/userinfo', book: @book %>




<div class="col-xs-9">
<h1>Books</h1>
	<table class="table">
		<thead>
			<tr>
				<th colspan="1"></th>
				<th>Title</th>
				<th>opinion</th>
			</tr>
		</thead>
		<% @user.books.each do |book| %>
		<tbody>
			<tr>
				<th>
					<%= attachment_image_tag book.user, :profile_image, size:"40x40", fallback: "no_iamge.jpg" %></th>
		
				<th><%= link_to book_path(book) do %>
					<%= book.title %></th><% end %>
				<th><%= book.body %></th>
			</tr>
		</tbody>
		<% end %>
	</table>
</div>
</div>
</div>
<%= render 'users/footer' %>