config/routes.rb
Rails.application.routes.draw do
 root :to => 'home#index'

get 'home/about', to: 'home#new'


devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}

	
	resources :users
	


	resources :books
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

belongs_to :user

validates :body, presence:true, length: { maximum:50 }
validates :title, presence:true




end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
before_action :correct_user,   only: [:edit, :update]

def index
	@book = Book.new
	@books = Book.all
	@user = current_user
	@users = User.all
end

def show
	@book = Book.find(params[:id])
	@books = Book.new
end

def create
	@book = Book.new(book_params)
	@book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was successfully saved."
	  redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
end

def destroy
	if @book = Book.find(params[:id])
	   @book.user_id == current_user.id
	   @book.destroy
	   flash[:notice] = "Book was successfully destroyed."
	   redirect_to books_path(@book.id)
	else
	   render :edit
	end
end


def edit
	@book = Book.find(params[:id])
	
end

def update
	@book = Book.find(params[:id])
	if @book.update(book_params)
	   flash[:notice] = "Book was successfully updated."
	   redirect_to book_path
	else
	   render :edit
	end
end

private
def book_params
	params.require(:book).permit(:title, :body)
end
def correct_user
	@book = Book.find(params[:id])
	unless
	@book.user == current_user
      redirect_to books_path
end
end
end

app/helpers/book_helper.rb
module BookHelper
end

app/views/books/_header1.html.erb
<header class="navbar navbar-fixed-top w-100 navbar-inverse">
	<div class="container">
        <nav class="nav navbar-nav navbar-left">
			<span class=" h3 text-muted">Bookers</span>
		</nav>
			<nav>
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
					<li class="nav-item"><%= link_to user_path(current_user.id) do %>
						<span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span></li><% end %>
					</li>
					<li class="nav-item"><%= link_to users_path do %>
						<span class="glyphicon glyphicon-user" aria-hidden="true"> Users</span></li><% end %>
					<li class="nav-item"><%= link_to books_path do %>
						<span class="glyphicon glyphicon-book" aria-hidden="true"> Books</span></li><% end %>
					<li class="nav-item"><%= link_to destroy_user_session_path, method: :delete do %><span class="glyphicon glyphicon-log-out" aria-hidden="true"> logout</span></li><% end %>
					<% else %>
					<li class="nav-item"><%= link_to root_path do %>
						<span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span></li><% end %>
					<li class="nav-item"><%= link_to home_about_path do %>
						<span class="glyphicon glyphicon-link" aria-hidden="true"> About</span></li><% end %>
					<li class="nav-item"><%= link_to new_user_registration_path do %><span class="glyphicon glyphicon-check" aria-hidden="true"> sign up</span></li><% end %>
					<li class="nav-item"><%= link_to new_user_session_path do %>
						<span class="glyphicon glyphicon-log-in" aria-hidden="true"> login</span></li><% end %>
					<% end %>
				</ul>
			</nav>
	</div>
</header>

	<div class="container">
		<div>
		<p id="notice"></p>
		</div>
	<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<table class="table">
			<tr><%= attachment_image_tag user, :profile_image, size:"100x100", fallback: "no_iamge.jpg" %></tr>
			<tr>
				<th>name</th>
				<th><%= current_user.name %></th>
			</tr>
			<tr>
				<th>introduction</th>
				<th><%= current_user.introduction %></th>
			</tr>
		</table>

app/views/books/_heder2.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
	<div class="container-fluid">
        <div class="nav navbar-nav navbar-left">
			<span class=" h3 text-muted">Bookers</span>
		</div>
			<nav>
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
					<li class="nav-item"><%= link_to user_path(current_user.id) do %>
						<span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span></li><% end %>
					</li>
					<li class="nav-item"><%= link_to users_path do %>
						<span class="glyphicon glyphicon-user" aria-hidden="true"> Users</span></li><% end %>
					<li class="nav-item"><%= link_to books_path do %>
						<span class="glyphicon glyphicon-book" aria-hidden="true"> Books</span></li><% end %>
					<li class="nav-item"><%= link_to destroy_user_session_path, method: :delete do %><span class="glyphicon glyphicon-log-out" aria-hidden="true"> logout</span></li><% end %>
					<% else %>
					<li class="nav-item"><%= link_to root_path do %>
						<span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span></li><% end %>
					<li class="nav-item"><%= link_to home_about_path do %>
						<span class="glyphicon glyphicon-link" aria-hidden="true"> About</span></li><% end %>
					<li class="nav-item"><%= link_to new_user_registration_path do %><span class="glyphicon glyphicon-check" aria-hidden="true"> sign up</span></li><% end %>
					<li class="nav-item"><%= link_to new_user_session_path do %>
						<span class="glyphicon glyphicon-log-in" aria-hidden="true"> login</span></li><% end %>
					<% end %>
				</ul>
			</nav>
	</div>
</nav>
<div class="container">
<div class="row">
<div class="col-xs-3">
	<h1>User info</h1>
		<table class="table">
			<tr><%= attachment_image_tag book.user, :profile_image, size:"100x100", fallback: "no_iamge.jpg" %></tr>
			<tr>
				<th>name</th>
				<th><%= (book.user).name %></th>
	
			</tr>
			<tr>
				<th>introduction</th>
				<th><%= (book.user).introduction %></th>
			</tr>
		</table>

		
		<%= link_to edit_user_path(book.user), class:'btn btn-primary btn-block' do %>
			
				<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
		<% end %>

app/views/books/_userinfo1.html.erb
<h2>New book</h2>
			<%= form_for(book) do |f| %>
			<% if book.errors.any? %>
				<div class="alert alert-danger" role class="alert">
					<p class="error-count"><%= book.errors.full_messages.count %>errors prohibited this book from being saved:</p>
				<ul>
					<% book.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
				</div>
<% end %>
			<%= f.label :title, "Title" %>
			<%= f.text_field :title %>

		    <%= f.label :body, "Body" %>
			<%= f.text_area :body %>

			<%= f.submit :class=> "btn btn-primary btn-block" %>
<% end %>
	</div>

app/views/books/edit.html.erb
<header class="navbar navbar-fixed-top w-100 navbar-inverse">
	<div class="container fluid">
        <nav class="nav navbar-nav navbar-left">
			<span class=" h3 text-muted">Bookers</span>
		</nav>
			<nav>
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
					<li class="nav-item"><%= link_to user_path(current_user.id) do %>
						<span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span></li><% end %>
					</li>
					<li class="nav-item"><%= link_to users_path do %>
						<span class="glyphicon glyphicon-user" aria-hidden="true"> Users</span></li><% end %>
					<li class="nav-item"><%= link_to books_path do %>
						<span class="glyphicon glyphicon-book" aria-hidden="true"> Books</span></li><% end %>
					<li class="nav-item"><%= link_to destroy_user_session_path, method: :delete do %><span class="glyphicon glyphicon-log-out" aria-hidden="true"> logout</span></li><% end %>
					<% else %>
					<li class="nav-item"><%= link_to root_path do %>
						<span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span></li><% end %>
					<li class="nav-item"><%= link_to home_about_path do %>
						<span class="glyphicon glyphicon-link" aria-hidden="true"> About</span></li><% end %>
					<li class="nav-item"><%= link_to new_user_registration_path do %><span class="glyphicon glyphicon-check" aria-hidden="true"> sign up</span></li><% end %>
					<li class="nav-item"><%= link_to new_user_session_path do %>
						<span class="glyphicon glyphicon-log-in" aria-hidden="true"> login</span></li><% end %>
					<% end %>
				</ul>
			</nav>
	</div>
</header>

<h1>Editing Books</h1>
<%= form_for(@book) do |f| %>

	<% if @book.errors.any? %>
	<div class="alert-alert-warinig">
		<p class="error-count"><%= @book.errors.full_messages.count %>errors prohibited this book from being saved:</p>
		<ul>
			<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>

    <% end %>
	<p>Title</p>
		<%= f.text_field :title %>
	<p>Opinion</p>
		<%= f.text_area :body %>

		<%= f.submit 'Update Book' %>
	<% end %>
	<%= link_to "Show", book_path(@book.id) %>
	<%= link_to "Back", books_path %>

	<%= render 'users/footer' %>

app/views/books/index.html.erb
<%= render 'books/header1', user: @user %>

		
		<%= link_to edit_user_path(current_user.id), class:'btn btn-primary btn-block' do %>
		<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
		<% end %>

<%= render 'books/userinfo1', book: @book %>
	<div class="col-xs-9">
		<h1>Books</h1>
			<table class="table">
				<thead>
					<tr>
						<th colspan="1"></th>
						<th>Title</th>
						<th>opinion</th>
					</tr>
				</thead>
				<% @books.each do |book| %>
				<tbody>
					<tr>
						<td><%= link_to user_path(book.user) do %>
						<%= attachment_image_tag book.user, :profile_image, size:"40x40", fallback: "no_iamge.jpg" %></td>
				<% end %>
						<td><%= link_to  book_path(book) do %>
							<i class="title"></i><%= book.title %></td>
				<% end %>
						
						<td><%= book.body %></td>
					</tr>
				</tbody>
	<% end %>
			</table>
		</div>
	</div>
</div>


<%= render 'users/footer' %>

app/views/books/show.html.erb
<%= render 'books/heder2', book: @book %>
<h2>New book</h2>
<%= form_for(@books) do |f| %>
<% if @book.errors.any? %>
<div class="alert alert-danger" role="alert">
	<p class="error-count"><%= @books.errors.full_messages.count %>errors prohibited this book from being saved:</p>
	<ul>
		<% @books.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>
<%= f.label :title, "Title" %>
<%= f.text_field :title %>

<%= f.label :body, "Body" %>
<%= f.text_area :body %>

<%= f.submit :class=> "btn btn-primary btn-block" %>
<% end %>
</div>




<div class="col-xs-9">
	<h1>Book detail</h1>
	<table class="table">
		<tr>
			<td><%= link_to user_path(@book.user) do %>
				<%= attachment_image_tag @book.user, :profile_image, size:"40x40", fallback: "no_iamge.jpg" %><br><%= (@book.user).name %></td>
				<% end %>
				<td><%= @book.title %>
				<td><%= @book.body %></td>
				<% if @book.user  == current_user %>
				<td><%= link_to "Edit", edit_book_path, class:'btn btn-success' %></td>
				<td><%= link_to "Destroy", book_path, method: :delete, data: { confirm:'Are you sure?'}, class:'btn btn-danger' %></td>
				<% end %>
			</tr>
		</table>
	</div>
</div>
</div>
<footer>
	<div class='container'>
		<div class='row'>
			<div class='col-xs-3 col-xs-offset-9'>
				<p>CopyRight Infratop.inc</p>
			</div>
		</div>
	</div>
</footer>